/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.record.domain.model;


import com.thee5176.ledger_command.record.domain.model.accounting.Accounting;
import com.thee5176.ledger_command.record.domain.model.credential.Credential;

import java.util.Arrays;
import java.util.List;

import org.jooq.Constants;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>accounting</code>.
     */
    public final Accounting ACCOUNTING = Accounting.ACCOUNTING;

    /**
     * The schema <code>credential</code>.
     */
    public final Credential CREDENTIAL = Credential.CREDENTIAL;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.asList(
            Accounting.ACCOUNTING,
            Credential.CREDENTIAL
        );
    }

    /**
     * A reference to the 3.20 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.20. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private static final String REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_20;
}
