services:
  postgres:
    image: "postgres:latest"
    container_name: postgres-command-record
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432"
