services:
  command_service:
    build: .
    container_name: springboot_cqrs_command
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/record"
      - "SPRING_DATASOURCE_USERNAME=springboot_admin"
      - "SPRING_DATASOURCE_PASSWORD=password"
    ports:
    - "8181:8080"
    depends_on:
    - postgres

  postgres:
    image: "postgres:latest"
    container_name: postgres-cqrs-db
    environment:
      - "POSTGRES_DB=record"
      - "POSTGRES_USER=springboot_admin"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5999:5432"
