services:
  postgres:
    image: "postgres:latest"
    container_name: postgres-command-record
    environment:
      - "POSTGRES_DB=record"
      - "POSTGRES_USER=springboot_admin"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5999:5432"
