/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.domain.model.accounting;


import com.thee5176.ledger_command.domain.model.DefaultCatalog;
import com.thee5176.ledger_command.domain.model.accounting.tables.CodeOfAccount;
import com.thee5176.ledger_command.domain.model.accounting.tables.LedgerItems;
import com.thee5176.ledger_command.domain.model.accounting.tables.Ledgers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Accounting extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>accounting</code>
     */
    public static final Accounting ACCOUNTING = new Accounting();

    /**
     * The table <code>accounting.code_of_account</code>.
     */
    public final CodeOfAccount CODE_OF_ACCOUNT = CodeOfAccount.CODE_OF_ACCOUNT;

    /**
     * The table <code>accounting.ledger_items</code>.
     */
    public final LedgerItems LEDGER_ITEMS = LedgerItems.LEDGER_ITEMS;

    /**
     * The table <code>accounting.ledgers</code>.
     */
    public final Ledgers LEDGERS = Ledgers.LEDGERS;

    /**
     * No further instances allowed
     */
    private Accounting() {
        super(DSL.name("accounting"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CodeOfAccount.CODE_OF_ACCOUNT,
            LedgerItems.LEDGER_ITEMS,
            Ledgers.LEDGERS
        );
    }
}
