/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.domain.model.accounting;


import com.thee5176.ledger_command.domain.model.accounting.tables.CodeOfAccount;
import com.thee5176.ledger_command.domain.model.accounting.tables.LedgerItems;
import com.thee5176.ledger_command.domain.model.accounting.tables.Ledgers;


/**
 * Convenience access to all tables in accounting.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>accounting.code_of_account</code>.
     */
    public static final CodeOfAccount CODE_OF_ACCOUNT = CodeOfAccount.CODE_OF_ACCOUNT;

    /**
     * The table <code>accounting.ledger_items</code>.
     */
    public static final LedgerItems LEDGER_ITEMS = LedgerItems.LEDGER_ITEMS;

    /**
     * The table <code>accounting.ledgers</code>.
     */
    public static final Ledgers LEDGERS = Ledgers.LEDGERS;
}
