/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.Domain.model;


import com.thee5176.ledger_command.Domain.model.tables.CodeOfAccount;
import com.thee5176.ledger_command.Domain.model.tables.FlywaySchemaHistory;
import com.thee5176.ledger_command.Domain.model.tables.LedgerItems;
import com.thee5176.ledger_command.Domain.model.tables.Ledgers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.code_of_account</code>.
     */
    public final CodeOfAccount CODE_OF_ACCOUNT = CodeOfAccount.CODE_OF_ACCOUNT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.ledger_items</code>.
     */
    public final LedgerItems LEDGER_ITEMS = LedgerItems.LEDGER_ITEMS;

    /**
     * The table <code>public.ledgers</code>.
     */
    public final Ledgers LEDGERS = Ledgers.LEDGERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CodeOfAccount.CODE_OF_ACCOUNT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            LedgerItems.LEDGER_ITEMS,
            Ledgers.LEDGERS
        );
    }
}
