/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.Domain.model;


import com.thee5176.ledger_command.Domain.model.tables.CodeOfAccount;
import com.thee5176.ledger_command.Domain.model.tables.FlywaySchemaHistory;
import com.thee5176.ledger_command.Domain.model.tables.LedgerItems;
import com.thee5176.ledger_command.Domain.model.tables.Ledgers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.code_of_account</code>.
     */
    public static final CodeOfAccount CODE_OF_ACCOUNT = CodeOfAccount.CODE_OF_ACCOUNT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.ledger_items</code>.
     */
    public static final LedgerItems LEDGER_ITEMS = LedgerItems.LEDGER_ITEMS;

    /**
     * The table <code>public.ledgers</code>.
     */
    public static final Ledgers LEDGERS = Ledgers.LEDGERS;
}
