/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.Domain.model.tables.pojos;


import com.thee5176.ledger_command.Domain.model.enums.BalanceType;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LedgerItems implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID ledgerId;
    private Integer coa;
    private Double amount;
    private BalanceType type;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public LedgerItems() {}

    public LedgerItems(LedgerItems value) {
        this.id = value.id;
        this.ledgerId = value.ledgerId;
        this.coa = value.coa;
        this.amount = value.amount;
        this.type = value.type;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public LedgerItems(
        UUID id,
        UUID ledgerId,
        Integer coa,
        Double amount,
        BalanceType type,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.ledgerId = ledgerId;
        this.coa = coa;
        this.amount = amount;
        this.type = type;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.ledger_items.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.ledger_items.id</code>.
     */
    public LedgerItems setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.ledger_items.ledger_id</code>.
     */
    public UUID getLedgerId() {
        return this.ledgerId;
    }

    /**
     * Setter for <code>public.ledger_items.ledger_id</code>.
     */
    public LedgerItems setLedgerId(UUID ledgerId) {
        this.ledgerId = ledgerId;
        return this;
    }

    /**
     * Getter for <code>public.ledger_items.coa</code>.
     */
    public Integer getCoa() {
        return this.coa;
    }

    /**
     * Setter for <code>public.ledger_items.coa</code>.
     */
    public LedgerItems setCoa(Integer coa) {
        this.coa = coa;
        return this;
    }

    /**
     * Getter for <code>public.ledger_items.amount</code>.
     */
    public Double getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.ledger_items.amount</code>.
     */
    public LedgerItems setAmount(Double amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Getter for <code>public.ledger_items.type</code>.
     */
    public BalanceType getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.ledger_items.type</code>.
     */
    public LedgerItems setType(BalanceType type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>public.ledger_items.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.ledger_items.created_at</code>.
     */
    public LedgerItems setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.ledger_items.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.ledger_items.updated_at</code>.
     */
    public LedgerItems setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LedgerItems other = (LedgerItems) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ledgerId == null) {
            if (other.ledgerId != null)
                return false;
        }
        else if (!this.ledgerId.equals(other.ledgerId))
            return false;
        if (this.coa == null) {
            if (other.coa != null)
                return false;
        }
        else if (!this.coa.equals(other.coa))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ledgerId == null) ? 0 : this.ledgerId.hashCode());
        result = prime * result + ((this.coa == null) ? 0 : this.coa.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LedgerItems (");

        sb.append(id);
        sb.append(", ").append(ledgerId);
        sb.append(", ").append(coa);
        sb.append(", ").append(amount);
        sb.append(", ").append(type);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
