/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.Domain.model.tables.records;


import com.thee5176.ledger_command.Domain.model.tables.Ledgers;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LedgersRecord extends UpdatableRecordImpl<LedgersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ledgers.id</code>.
     */
    public LedgersRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.ledgers.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.ledgers.date</code>.
     */
    public LedgersRecord setDate(LocalDate value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.ledgers.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.ledgers.description</code>.
     */
    public LedgersRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.ledgers.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ledgers.created_at</code>.
     */
    public LedgersRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.ledgers.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.ledgers.updated_at</code>.
     */
    public LedgersRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.ledgers.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LedgersRecord
     */
    public LedgersRecord() {
        super(Ledgers.LEDGERS);
    }

    /**
     * Create a detached, initialised LedgersRecord
     */
    public LedgersRecord(UUID id, LocalDate date, String description, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Ledgers.LEDGERS);

        setId(id);
        setDate(date);
        setDescription(description);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised LedgersRecord
     */
    public LedgersRecord(com.thee5176.ledger_command.Domain.model.tables.pojos.Ledgers value) {
        super(Ledgers.LEDGERS);

        if (value != null) {
            setId(value.getId());
            setDate(value.getDate());
            setDescription(value.getDescription());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
