/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.domain.model.credential.tables.records;


import com.thee5176.ledger_command.domain.model.credential.enums.Authority;
import com.thee5176.ledger_command.domain.model.credential.tables.User;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>credential.user.id</code>.
     */
    public UserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>credential.user.username</code>.
     */
    public UserRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>credential.user.password</code>.
     */
    public UserRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>credential.user.is_enabled</code>.
     */
    public UserRecord setIsEnabled(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.is_enabled</code>.
     */
    public Boolean getIsEnabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>credential.user.is_account_non_expired</code>.
     */
    public UserRecord setIsAccountNonExpired(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.is_account_non_expired</code>.
     */
    public Boolean getIsAccountNonExpired() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>credential.user.is_credentials_non_expired</code>.
     */
    public UserRecord setIsCredentialsNonExpired(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.is_credentials_non_expired</code>.
     */
    public Boolean getIsCredentialsNonExpired() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>credential.user.is_account_non_locked</code>.
     */
    public UserRecord setIsAccountNonLocked(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.is_account_non_locked</code>.
     */
    public Boolean getIsAccountNonLocked() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>credential.user.firstname</code>.
     */
    public UserRecord setFirstname(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>credential.user.lastname</code>.
     */
    public UserRecord setLastname(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.lastname</code>.
     */
    public String getLastname() {
        return (String) get(8);
    }

    /**
     * Setter for <code>credential.user.email</code>.
     */
    public UserRecord setEmail(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.email</code>.
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>credential.user.authorities</code>.
     */
    public UserRecord setAuthorities(Authority[] value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>credential.user.authorities</code>.
     */
    public Authority[] getAuthorities() {
        return (Authority[]) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String username, String password, Boolean isEnabled, Boolean isAccountNonExpired, Boolean isCredentialsNonExpired, Boolean isAccountNonLocked, String firstname, String lastname, String email, Authority[] authorities) {
        super(User.USER);

        setId(id);
        setUsername(username);
        setPassword(password);
        setIsEnabled(isEnabled);
        setIsAccountNonExpired(isAccountNonExpired);
        setIsCredentialsNonExpired(isCredentialsNonExpired);
        setIsAccountNonLocked(isAccountNonLocked);
        setFirstname(firstname);
        setLastname(lastname);
        setEmail(email);
        setAuthorities(authorities);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(com.thee5176.ledger_command.domain.model.credential.tables.pojos.User value) {
        super(User.USER);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setPassword(value.getPassword());
            setIsEnabled(value.getIsEnabled());
            setIsAccountNonExpired(value.getIsAccountNonExpired());
            setIsCredentialsNonExpired(value.getIsCredentialsNonExpired());
            setIsAccountNonLocked(value.getIsAccountNonLocked());
            setFirstname(value.getFirstname());
            setLastname(value.getLastname());
            setEmail(value.getEmail());
            setAuthorities(value.getAuthorities());
            resetTouchedOnNotNull();
        }
    }
}
