/*
 * This file is generated by jOOQ.
 */
package com.thee5176.record.springboot_cqrs_command.model;


import com.thee5176.record.springboot_cqrs_command.model.tables.CodeOfAccount;
import com.thee5176.record.springboot_cqrs_command.model.tables.Entries;
import com.thee5176.record.springboot_cqrs_command.model.tables.FlywaySchemaHistory;
import com.thee5176.record.springboot_cqrs_command.model.tables.Transactions;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * 勘定科目(COA) - フレームワークの科目を活用する
     * - 青色申告: https://biz.moneyforward.com/tax_return/basic/12079/
     * - IFRS: https://www.ifrs-gaap.com/basic-ifrs-coa
     * - GAAP: https://www.ifrs-gaap.com/basic-us-gaap-coa

     */
    public final CodeOfAccount CODE_OF_ACCOUNT = CodeOfAccount.CODE_OF_ACCOUNT;

    /**
     * エントリー：取引内の科目だけの関係で分ける
     * 
     * ttps://www.geeksforgeeks.org/accountancy/accounting-entry-meaning-types-advantages-examples/

     */
    public final Entries ENTRIES = Entries.ENTRIES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * 取引： 取引に少なくとも2つの科目が関係し、一つが借方 他のは貸方
     * 
     * ttps://www.geeksforgeeks.org/accountancy/accounting-entry-meaning-types-advantages-examples/

     */
    public final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CodeOfAccount.CODE_OF_ACCOUNT,
            Entries.ENTRIES,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Transactions.TRANSACTIONS
        );
    }
}
