/*
 * This file is generated by jOOQ.
 */
package com.thee5176.record.springboot_cqrs_command.model;


import com.thee5176.record.springboot_cqrs_command.model.tables.CodeOfAccount;
import com.thee5176.record.springboot_cqrs_command.model.tables.Entries;
import com.thee5176.record.springboot_cqrs_command.model.tables.FlywaySchemaHistory;
import com.thee5176.record.springboot_cqrs_command.model.tables.Transactions;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 勘定科目(COA) - フレームワークの科目を活用する
     * - 青色申告: https://biz.moneyforward.com/tax_return/basic/12079/
     * - IFRS: https://www.ifrs-gaap.com/basic-ifrs-coa
     * - GAAP: https://www.ifrs-gaap.com/basic-us-gaap-coa

     */
    public static final CodeOfAccount CODE_OF_ACCOUNT = CodeOfAccount.CODE_OF_ACCOUNT;

    /**
     * エントリー：取引内の科目だけの関係で分ける
     * 
     * ttps://www.geeksforgeeks.org/accountancy/accounting-entry-meaning-types-advantages-examples/

     */
    public static final Entries ENTRIES = Entries.ENTRIES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * 取引： 取引に少なくとも2つの科目が関係し、一つが借方 他のは貸方
     * 
     * ttps://www.geeksforgeeks.org/accountancy/accounting-entry-meaning-types-advantages-examples/

     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;
}
