/*
 * This file is generated by jOOQ.
 */
package com.thee5176.ledger_command.domain.model.credential;


import com.thee5176.ledger_command.domain.model.credential.tables.User;


/**
 * Convenience access to all tables in credential.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>credential.user</code>.
     */
    public static final User USER = User.USER;
}
